version: '3.0'

networks:
  app:
    driver: bridge


volumes:
  db-data:
    driver: local

services:
  db_pg:
    image: postgres:16
    networks:
    - app
    env_file:
      - .env
    ports:
      - '5437:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    networks:
      - app
    depends_on:
      - db_pg
    env_file:
      - .env
    ports:
      - '8081:8081'