spring.application.name=PaymentApp

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${HOST}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

server.port=8081
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
server.error.include-message=always

spring.docker.compose.profiles.active=db_pg
spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.start.log-level=info
spring.docker.compose.start.command=up